//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxeCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string ProfileImageUrl { get; set; }
        public bool AcceptTerms { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Role { get; set; }
    }
}
